"""Phase 4C-3B: Durable Customer Intake

Revision ID: 64b3e0f731ab
Revises: 2a540c6f8a6e
Create Date: 2026-07-13 21:03:10.748552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64b3e0f731ab'
down_revision: Union[str, None] = '2a540c6f8a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_intake_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('encryption_version', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(status != 'cancelled') OR (cancelled_at IS NOT NULL)", name='ck_draft_cancelled_time'),
    sa.CheckConstraint("(status != 'consumed') OR (consumed_at IS NOT NULL)", name='ck_draft_consumed_time'),
    sa.CheckConstraint("(status != 'invalidated') OR (invalidated_at IS NOT NULL)", name='ck_draft_invalidated_time'),
    sa.CheckConstraint("status IN ('pending', 'consumed', 'expired', 'cancelled', 'invalidated')", name='ck_draft_status'),
    sa.CheckConstraint('current_step >= 0', name='ck_draft_current_step_pos'),
    sa.CheckConstraint('encryption_version > 0', name='ck_draft_enc_ver_pos'),
    sa.CheckConstraint('expires_at > created_at', name='ck_draft_expires_after_created'),
    sa.CheckConstraint('quantity > 0', name='ck_draft_quantity_pos'),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_checkout_intake_drafts_goods_id'), 'checkout_intake_drafts', ['goods_id'], unique=False)
    op.create_index(op.f('ix_checkout_intake_drafts_public_token'), 'checkout_intake_drafts', ['public_token'], unique=True)
    op.create_index(op.f('ix_checkout_intake_drafts_user_id'), 'checkout_intake_drafts', ['user_id'], unique=False)
    op.create_index('ix_draft_goods_status', 'checkout_intake_drafts', ['goods_id', 'status'], unique=False)
    op.create_index('ix_draft_status_expires', 'checkout_intake_drafts', ['status', 'expires_at'], unique=False)
    op.create_index('ix_draft_user_goods_status', 'checkout_intake_drafts', ['user_id', 'goods_id', 'status'], unique=False)
    op.create_index('ix_draft_user_status_updated', 'checkout_intake_drafts', ['user_id', 'status', 'updated_at'], unique=False)
    op.create_table('manual_fulfillment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')", name='ck_mfj_status'),
    sa.CheckConstraint('version > 0', name='ck_mfj_version_pos'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_table('order_customer_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('original_field_id', sa.Integer(), nullable=True),
    sa.Column('field_key_snapshot', sa.String(length=64), nullable=False),
    sa.Column('label_i18n_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('field_type_snapshot', sa.String(length=20), nullable=False),
    sa.Column('scope_snapshot', sa.String(length=20), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('masked_preview', sa.String(length=255), nullable=False),
    sa.Column('encryption_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_snapshot = 'per_order' AND unit_index = 0) OR (scope_snapshot = 'per_unit' AND unit_index > 0)", name='ck_oci_scope_unit_index'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_field_id'], ['product_customer_fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'field_key_snapshot', 'unit_index', name='uq_oci_item_key_unit')
    )
    op.create_index(op.f('ix_order_customer_inputs_order_id'), 'order_customer_inputs', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_customer_inputs_order_item_id'), 'order_customer_inputs', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_customer_inputs_original_field_id'), 'order_customer_inputs', ['original_field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade guard for Phase 4C-3B
    conn = op.get_bind()
    
    res = conn.execute(sa.text("SELECT COUNT(1) FROM checkout_intake_drafts WHERE status = 'consumed'"))
    if res.scalar() > 0:
        raise RuntimeError("Cannot downgrade: There are consumed CheckoutIntakeDraft records. Manual fulfillment data would be lost.")
        
    res = conn.execute(sa.text("SELECT COUNT(1) FROM order_customer_inputs"))
    if res.scalar() > 0:
        raise RuntimeError("Cannot downgrade: There are OrderCustomerInput records. Manual fulfillment data would be lost.")
        
    res = conn.execute(sa.text("SELECT COUNT(1) FROM manual_fulfillment_jobs"))
    if res.scalar() > 0:
        raise RuntimeError("Cannot downgrade: There are ManualFulfillmentJob records. Manual fulfillment data would be lost.")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_customer_inputs_original_field_id'), table_name='order_customer_inputs')
    op.drop_index(op.f('ix_order_customer_inputs_order_item_id'), table_name='order_customer_inputs')
    op.drop_index(op.f('ix_order_customer_inputs_order_id'), table_name='order_customer_inputs')
    op.drop_table('order_customer_inputs')
    op.drop_table('manual_fulfillment_jobs')
    op.drop_index('ix_draft_user_status_updated', table_name='checkout_intake_drafts')
    op.drop_index('ix_draft_user_goods_status', table_name='checkout_intake_drafts')
    op.drop_index('ix_draft_status_expires', table_name='checkout_intake_drafts')
    op.drop_index('ix_draft_goods_status', table_name='checkout_intake_drafts')
    op.drop_index(op.f('ix_checkout_intake_drafts_user_id'), table_name='checkout_intake_drafts')
    op.drop_index(op.f('ix_checkout_intake_drafts_public_token'), table_name='checkout_intake_drafts')
    op.drop_index(op.f('ix_checkout_intake_drafts_goods_id'), table_name='checkout_intake_drafts')
    op.drop_table('checkout_intake_drafts')
    # ### end Alembic commands ###
