"""Phase 4C-2 Orders

Revision ID: 88fa0a98da99
Revises: 25c3a9be3a10
Create Date: 2026-07-12 17:19:32.295226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fa0a98da99'
down_revision: Union[str, None] = '25c3a9be3a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promo_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'processing', 'completed', 'cancelled', 'failed', 'refunded')", name='ck_order_status'),
    sa.CheckConstraint('discount_total <= subtotal', name='ck_order_discount_max'),
    sa.CheckConstraint('discount_total >= 0', name='ck_order_discount_pos'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_subtotal_pos'),
    sa.CheckConstraint('total >= 0', name='ck_order_total_pos'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_order_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_order_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_public_id'), 'orders', ['public_id'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('product_description_snapshot', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("fulfillment_status IN ('pending', 'processing', 'delivered', 'failed', 'cancelled', 'refunded')", name='ck_order_item_fstatus'),
    sa.CheckConstraint('discount_total <= subtotal', name='ck_order_item_discount_max'),
    sa.CheckConstraint('discount_total >= 0', name='ck_order_item_discount_pos'),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_qty_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_item_subtotal_pos'),
    sa.CheckConstraint('total >= 0', name='ck_order_item_total_pos'),
    sa.ForeignKeyConstraint(['item_id'], ['goods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_item_fstatus', 'order_items', ['fulfillment_status'], unique=False)
    op.create_index('ix_order_item_order_fstatus', 'order_items', ['order_id', 'fulfillment_status'], unique=False)
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('bought_goods', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('bought_goods', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bought_goods_order_id'), 'bought_goods', ['order_id'], unique=False)
    op.create_index(op.f('ix_bought_goods_order_item_id'), 'bought_goods', ['order_item_id'], unique=False)
    op.create_foreign_key(None, 'bought_goods', 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bought_goods', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bought_goods', type_='foreignkey')
    op.drop_constraint(None, 'bought_goods', type_='foreignkey')
    op.drop_index(op.f('ix_bought_goods_order_item_id'), table_name='bought_goods')
    op.drop_index(op.f('ix_bought_goods_order_id'), table_name='bought_goods')
    op.drop_column('bought_goods', 'order_item_id')
    op.drop_column('bought_goods', 'order_id')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_index('ix_order_item_order_fstatus', table_name='order_items')
    op.drop_index('ix_order_item_fstatus', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_public_id'), table_name='orders')
    op.drop_index('ix_order_user_status', table_name='orders')
    op.drop_index('ix_order_user_created', table_name='orders')
    op.drop_index('ix_order_status_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
