"""phase_3_editable_texts

Revision ID: ae15bd167ffb
Revises: 36995ede2291
Create Date: 2026-07-09 22:06:51.540799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""phase_3_editable_texts

Revision ID: ae15bd167ffb
Revises: 36995ede2291
Create Date: 2026-07-09 22:06:51.540799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae15bd167ffb'
down_revision: Union[str, None] = '36995ede2291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_root_title', sa.String(length=255), nullable=True),
    sa.Column('shop_root_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    op.drop_table('store_settings')
    # ### end Alembic commands ###
