"""fix_bought_goods_schema

Revision ID: aed0950a0170
Revises: 88fa0a98da99
Create Date: 2026-07-12 19:51:14.870386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed0950a0170'
down_revision: Union[str, None] = '88fa0a98da99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bought_goods', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('bought_goods', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bought_goods_order_id'), 'bought_goods', ['order_id'], unique=False)
    op.create_index(op.f('ix_bought_goods_order_item_id'), 'bought_goods', ['order_item_id'], unique=False)
    op.create_foreign_key('fk_bought_goods_order_id', 'bought_goods', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_bought_goods_order_item_id', 'bought_goods', 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bought_goods_order_item_id', 'bought_goods', type_='foreignkey')
    op.drop_constraint('fk_bought_goods_order_id', 'bought_goods', type_='foreignkey')
    op.drop_index(op.f('ix_bought_goods_order_item_id'), table_name='bought_goods')
    op.drop_index(op.f('ix_bought_goods_order_id'), table_name='bought_goods')
    op.drop_column('bought_goods', 'order_item_id')
    op.drop_column('bought_goods', 'order_id')
    # ### end Alembic commands ###
